name: Generate Pickles

on:
    push:
        branches:
            - main
    workflow_dispatch:

jobs:
    generate-pickles:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout repository
          uses: actions/checkout@v3
    
        - name: Set up Python
          uses: actions/setup-python@v4
          with:
            python-version: '3.13'
    
        - name: Generate Pickles
          run: |
            python evil-pickle.py linux linux-pickle.pkl
            python evil-pickle.py windows windows-pickle.pkl
    
        - name: Commit and push changes
          run: |
            git config --global user.name 'GitHub Actions'
            git config --global user.email 'actions@github.com'
            git add pkl/
            git commit -m "chore: Updated pickles [skip ci]" || echo "No changes to commit"
            git push